######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 6 16:27:22 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CONFIG += console
LIBS += -L/usr/lib -lqjson
# Input
HEADERS += googled.h
SOURCES += googled.cpp
